= Транслитерация для идентификаторов

Во многих проектах для обозначения идентификаторов целесообразно использовать русские наименования. Однако большинство языков программирования не поддерживают использование русских букв в названиях идентификаторов.

В наименованиях веб-страниц также не всегда целесообразно использовать русские буквы. При вставке в документ кириллические символы кодируются, делая наименование страницы нечитаемым, например, угадайте, что означает http://xn--j1ail.xn--p1ai/.

В таких случаях целесообразно использование транслитерации. Правила транслитерации должны отвечать следующим требованиям.

* Текст должен быть читаемым людьми, знающими, как произносятся латинские буквы на английском языке (просто потому, что английский язык в настоящее время является неформальным стандартом для международной коммуникации).
* Текст не должен содержать символов, не относящихся к буквам латинского алфавита, в том числе диакритических знаков. Только эти буквы можно уверенно использовать в идентификаторах любых языков программирования.
* Правила транслитерации должны обладать свойством изоморфизма, т.е. обратное преобразования из строки, написанной латинскими символами, в строку, написанную кириллическими символами, должно давать исходную строку. Например в загранпаспорте буквы «e» и «э» и обозначаются латинским «e». Таким образом, вид страусов «Emu» при преобразовании в кириллическую строку может превратиться в «Ему», а не «Эму».

В настоящее время существует множество систем транслитерации, но ни одна из них не отвечает указанным требованиям.

Наилучшим образом этим правилами соответствует ГОСТ 7.79-2000 (система Б). Однако она обладает следующими недостатками.

. Буква «х» (ха) кодируется латинским символом «x» (экс). Например слово «храпит» кодируется как «xrapit»: читается не очевидным образом.
. Буквы «ь», «ы», «ъ», «э» кодируются с использованием символа ``` (именно гравис, не апостроф).
. Для буквы «ц» допускается два варианта написания: «c», «cz».

Мы решили, что кодирование буквы «х» хотя и ухудшает читаемость текста, но не настолько, чтобы отходить от требований ГОСТ.

Для букв «ь», «ы», «ъ», «э» мы используем следующую систему кодирования:

* ь -- q (вместо ```): если перевернуть строчную букву q, мы как раз и получим мягкий знак;
* ы -- yh (вместо `y``);
* ъ -- qq (вместо ````);
* э -- eh (вместо `e``).

Для кодирования буквы «ц» принимаем только один вариант -- «cz».




