
:toc: macro
:toc-title:

*Руководство стиля* (или *Styleguide*) — набор стандартов и правил, которых нужно придерживаться при создании или дополнении справочных разделов для информационно-аналитической системы «Безопасность полётов» (ИАС БП).

[NOTE]
====
Данное руководство стиля подготовлено совместно с компанией http://documentat.io/[documentat.io].
====

toc::[]

== Общие рекомендации ==
Основными целями справочных руководств для ИАС БП являются демонстрация возможностей системы и обучение пользователей основным сценариям работы. Таким образом, документ должен быть удобен как для последовательного чтения, так и для поиска конкретной инструкции.

- Рекомендуется использовать не более трех уровней вложенности заголовков. Описание шагов инструкций не выносятся в качестве заголовка, используются нумерованные списки.
- При описании схожих сценариев объединять их в один, но с подробной детализацией в различающихся шагах.
- Надо описывать только те поля, работа с которыми может вызвать затруднения.
- По умолчанию не описываются параметры поиска из-за их очевидности.
- По умолчанию не описываются карточки объектов, но если в карточках присутствуют важные поля/метки, то дать их описание.
- В новом разделе при первом упоминании базовых действий в интерфейсе программы ссылаться на их описание в главе 3 «Общие элементы интерфейса».
- В новом разделе при вводе нового термина давать в самом начале его описание, даже если оно уже есть в главе 1.1 «Определения, обозначения и сокращения».

Перед написанием или дополнением раздела автору следует ознакомиться с содержанием следующих статей в руководстве пользователя:

- Глава 1.1 «Определения, обозначения и сокращения»;
- Глава 3 «Общие элементы интерфейса».

=== Шаблон описания рабочего места ===
В данном разделе представлено описание полной структуры рабочего места, по которому оформляются все страницы справки для ИАС БП. 

. *Назначение рабочего места* _(обязательно)_ +
В начале описания каждого рабочего места следует сообщить читателю вводную информацию:
* Цели использования рабочего места; 
* Кому доступно рабочее место, нужно ли дополнительное разрешение доступа для работы в нем;
* Дополнительные условия для начала работы в рабочем месте (например, создание объектов в других рабочих местах).
. *Локальное оглавление* _(опционально)_ +
Если описание рабочего места довольно объёмное (более двух экранов), то пользователю лучше показать его полную структуру для упрощения поиска информации.
. *Описание основной таблицы рабочего места* _(обязательно)_
* Список объектов, который показывается в таблице; 
* Настраивается ли отображение данных в таблице дополнительными фильтрами;
* Перечень колонок таблицы с описанием (если оно необходимо); 
* Если в колонках таблицы присутствуют метки или флажки, то обязательно указать их легенду.
. *Описание панели инструментов* _(обязательно)_ +
Если в рабочем месте есть дополнительные функции для работы с объектами основной таблицы, то нужно разместить перечень этих функций с их описанием:
* Всегда ли доступна эта функция (ограничения по ролям); 
* Условия, необходимые для её работы (ввод дополнительных параметров);
* Запрашивается ли подтверждение действия для критичных операций (например, удаление). 
. *Описание редакторов/карточек* _(опционально)_ +
Если в карточках объектов таблицы есть неочевидные поля/метки/флажки, то их нужно описать:
* Назначение поля/метки;
* Доступность заполнения/выставления + зависимости от других полей/меток;
* Ограничение по формату (максимальные значения, определённые типы, язык, неиспользуемые символы).
. *Описание сценариев использования* _(опционально)_ +
Если есть особые сценарии работы пользователя в рабочем месте, то их следует описать в этом блоке:
* Ссылку на описание сценария вынести в локальное оглавление (пункт 2);
* Дать краткое описание сценария и возможного конечного результата;
* Указать пошаговый алгоритм выполнения действий (см. критерии описания сценариев). +
+
Также в разделе можно описать решение возможных типовых ошибок пользователя.
. *Связи между другими рабочими местами* _(опционально)_ +
Указывать в этом разделе другие рабочие места, которые влияют на работу в этом рабочем месте (например, требуется создание дополнительных объектов).

== Оформление текста ==
Для быстрого ориентирования в тексте некоторые сущности могут быть выделены особым начертанием, цветом или иными эффектами. Ниже представлена таблица правил оформления:

[cols="4",options="header,footer,autowidth"]
.Правила оформления 
|===
^|Элемент/Сущность
^|Правила
^|Пример
^|Оформление в Asciidoc

s|Название термина
a|
- Курсив при первом упоминании,
- Жирный при расшифровке термина.
|В тексте есть _запятые_. +
*Запятая* — это знак препинания.
|В тексте есть \_запятые_. +
\*Запятая* — это знак препинания.

s|Комбинации клавиш
a|
- Курсив, 
- Базовый цвет,
- Без кавычек.
|_Ctrl+Shift+Delete_
|\_Ctrl+Shift+Delete_

s|Переходы в программе
a|
- Курсив,
- Синий цвет,
- Используется стрелка «→» для связи.
|[blue]#_Отчеты → Рейтинг → Рейтинг ТО_#
|[blue]\#\_Отчеты → Рейтинг → Рейтинг ТО_#

s|Названия кнопок
a|
- Моноширинный текст с фоном, 
- Квадратные скобки.
|`[Кнопка]`
|\`[Кнопка]`

s|Блок команд/код
a| Используется конструкция "Блок кода"
a|
----
ping mail.ru -t
----
|---- + 
ping mail.ru -t + 
----

|===

== Оформление объектов ==

=== Списки ===

В списках выделяют две основные сущности — _предваряющий элемент_ и _элементы списка_. +
*Предваряющий элемент* — слово или предложение, которое описывает список, находится непосредственно перед ним и отделяется двоеточием или точкой. Двоеточие используется, если присутствует обобщающее слово или предложение, точка — если связь с элементами списка слабая. Если предваряющий элемент заканчивается двоеточием, не рекомендуется оставлять в конце предваряющего элемента предлог. +
*Элементы списка* — составляющая часть перечня. Элементы отделяются друг от друга запятой, точкой с запятой или точкой. В конце элемента перечня ставится:

- _запятая_, если элемент прост, т. е. состоит из одного или нескольких слов и не содержит знаков препинания;
- _точка с запятой_, если элемент содержит знаки препинания и состоит не более чем из одного предложения; 
- _точка_, если элемент состоит из нескольких предложений или это последний элемент списка.

Общие правила для списков:

- По умолчанию всегда используются _ненумерованные списки_. Такие списки формируются символом «-».
- _Нумерованные списки_ используются только при описании последовательности действий или объектов, на номера которых надо будет ссылаться в будущем. Также нумерованные списки используются при описании последовательных инструкций и сценариев действий. Задаются с помощью символа «.».
- Если список представляет собой перечень элементов и их описание, то название элемента выделятся жирным начертанием, длинное тире «—» отделяет название и описание.

NOTE: Подробнее о правилах оформления списков в Asciidoc можно прочитать в главах https://asciidoctor.org/docs/user-manual/#unordered-lists[«Unordered lists»] и https://asciidoctor.org/docs/user-manual/#ordered-lists[«Ordered lists»] официального руководства. 

=== Таблицы ===

Правила для использования таблиц в руководстве:

- Для каждой таблицы указывается описание. В Asciidoc-разметке описание ставится перед таблицей через символ «.».
- Обязательно указывать заголовки для столбцов таблицы, выравнивать их по центру (атрибут «^»). 
+
NOTE: Подробнее об атрибутах оформления таблиц в Asciidoc можно прочитать в главе  https://asciidoctor.org/docs/user-manual/#summary-tables[«Summary tables»] официального руководства. 
+
- Названия элементов таблицы выделять жирным, описание идёт обычным начертанием.

.Оформление таблицы в Asciidoc и результат после преобразования 
=====================================
[cols="2",options="header,footer,autowidth"] +
.Описание к таблице +
|=== +
^|Заголовок для элементов таблицы +
^|Свойства элементов таблицы +
s|Элемент №1 +
a|Описание свойств для элемента №1 +
s|Элемент №2 +
a|Описание свойств для элемента №2 +
|=== + 

[cols="2",options="header,footer,autowidth"]
.Описание к таблице 
|===
^|Заголовок для элементов таблицы
^|Свойства элементов таблицы
s|Элемент №1
a|Описание свойств для элемента №1

s|Элемент №2
a|Описание свойств для элемента №2
|===
=====================================

=== Рисунки и скриншоты ===

Рисунки и скриншоты в документе следует размещать с учётом следующих правил:

- Рисунок размещается после блока с поясняющей информацией;
- Для рисунка всегда указывается его описание;
- Скриншот должен быть без лишних деталей и отображать только информацию об описываемом разделе;
- Если в разделе ИАС, на который ссылается скриншот, имеются поля для заполнения, их рекомендуется наполнить примерным содержимым.

NOTE: Подробнее о правилах вставки изображений в Asciidoc можно прочитать в главе https://asciidoctor.org/docs/user-manual/#images[«Images»] официального руководства. 

=== Ссылки ===

При использовании в тексте ссылок на сторонние ресурсы для удобства чтения их рекомендуется переименовывать. Для этого в AsciiDoc сразу после ссылки в квадратные скобки заключите её описание.

NOTE: Подробнее о правилах оформления ссылок в Asciidoc можно прочитать в главе https://asciidoctor.org/docs/user-manual/#url[«URL»] официального руководства. 

.Оформление внешней ссылки в Asciidoc и результат после преобразования 
==========================
\https://www.google.com/ [Поиск в Google] → https://www.google.com/[Поиск в Google]
==========================

=== Информационные вставки ===

Для акцентирования внимания на каких-то специфических моментах в описании можно использовать информационные вставки. В Asciidoc это реализовано через выделение блока текста с помощью указания одного из следующих типов:

- *NOTE:* — обычный информационный блок;
- *TIP:* — Блок «_подсказка_»;
- *IMPORTANT:* — Блок «_важно_»;
- *CAUTION:* — Блок «_предостережение_»;
- *WARNING:* — Блок «_внимание_».

NOTE: Подробнее о правилах оформления блоков текста в Asciidoc можно прочитать в главе https://asciidoctor.org/docs/user-manual/#blocks[«Blocks»] официального руководства. 

Примеры использования форматирования текста таким способом:

- Ссылка на подробное описание в другое руководство или раздел в текущем документе;
- Зависимости между выполнениями действий;
- Рекомендации по действиям в случае редкой ошибки;
- Детали технической реализации, которые могут быть полезны администратору, но не влияют напрямую на его работу с системой.

== Принципы описания и сборки документации ==

Вся документация оформляется в виде набора текстов на базе языка разметки Asciidoc, которые потом конвертируются в файлы PDF и HTML форматов. При написании следует использовать только те возможности Asciidoc, которые поддерживаются одновременно и в PDF-, и в HTML-версиях файлов.

WARNING: Запрещено использование активных и динамических элементов (gif-изображения, спойлеры, кнопки), так как они не будут воспроизводиться в PDF-документах. 
